import { MenuI } from 'app/shared/models/menu models/menu.interface';

export const ADMIN_NAVIGATIONS: MenuI[] = [
    {
        id: 'Dashboard',
        title: 'Dashboard',
        type: 'basic',
        icon: 'heroicons_outline:home',
        link: '/dashboard',
        module: ['Dashboard'],
        svg: 'svg_1',
    },
    {
        id: 'Money Transfer',
        title: 'Money Transfer',
        type: 'basic',
        icon: 'mat_outline:money',
        link: '/money-transfer',
        module: ['money-transfer'],
        svg: 'svg_2',
    },
    {
        id: 'AEPS',
        title: 'AEPS',
        type: 'basic',
        icon: 'heroicons_outline:finger-print',
        link: '/aeps',
        module: ['aeps'],
        svg: 'svg_3',
    },
    {
        id: 'CMS',
        title: 'CMS',
        type: 'basic',
        icon: 'mat_outline:monetization_on',
        link: '/cms',
        module: ['cms'],
        svg: 'svg_4',
    },
    {
        id: 'Recharge',
        title: 'Recharge',
        type: 'basic',
        icon: 'mat_outline:mobile_friendly',
        link: '/recharge',
        module: ['recharge'],
        svg: 'svg_5',
    },
    {
        id: 'Collect Money',
        title: 'Collect Money',
        type: 'basic',
        icon: 'heroicons_outline:currency-rupee',
        link: '/collect-money',
        module: ['collect-money'],
        svg: 'svg_6',
    },
    {
        id: 'Gold',
        title: 'Gold',
        type: 'basic',
        icon: 'mat_outline:real_estate_agent',
        link: '/gold',
        module: ['gold'],
        svg: 'svg_7',
    },
    {
        id: 'Bill Payments',
        title: 'Bill Payments',
        type: 'basic',
        icon: 'heroicons_outline:document-text',
        link: '/bill-payments',
        module: ['bill-payments'],
        svg: 'svg_8',
    },
    {
        id: 'Bank',
        title: 'Bank ',
        type: 'basic',
        icon: 'mat_solid:account_balance',
        link: '/bank-details',
        module: ['bank-details'],
        svg: 'svg_9',
    },

    {
        id: 'Cashin',
        title: 'Load Money (CashIn) ',
        type: 'basic',
        icon: 'mat_outline:system_update',
        link: '/cash-in',
        module: ['cashin'],
        svg: 'cashin',
    },
    // {
    //     id: 'Cashout',
    //     title: 'Cashout ',
    //     type: 'basic',
    //     icon: 'mat_outline:mobile_screen_share',
    //     link: '/cash-out',
    //     module: ['cashout'],
    //     svg: 'svg_14',
    // },
    {
        id: 'Payout',
        title: 'Payout ',
        type: 'basic',
        icon: 'mat_solid:account_payout',
        link: '/payout',
        module: ['payout'],
        svg: 'svg_10',
    },
    {
        id: 'Request Credits',
        title: 'Request Credits ',
        type: 'basic',
        icon: 'mat_solid:account_payout',
        link: '/request-credit',
        module: ['request-credit'],
        svg: 'svg_13'
    },
    {
        id: 'Withdrawal Limit',
        title: 'Withdrawal',
        type: 'basic',
        icon: 'mat_solid:account_payout',
        link: '/withdrawal-limit',
        module: ['withdrawal-limit'],
        svg: 'svg_12',
    },
    {
        id: '',
        title: 'Payment Gateway',
        type: 'collapsable',
        icon: 'mat_outline:credit_card',
        svg: 'svg_11',
        children: [
            {
                id: 'PG Link',
                title: 'PG Link',
                type: 'basic',
                icon: 'mat_outline:arrow_right',
                hidden: false,
                link: '/payment-gateway',
                module: ['pg-link'],
            },
            {
                id: 'PG Link-1',
                title: 'PG Link-1',
                type: 'basic',
                icon: 'mat_outline:arrow_right',
                hidden: false,
                link: '/pg-link/1',
                module: ['pg-link-1'],
            },
            {
                id: 'PG Link-2',
                title: 'PG Link-2',
                type: 'basic',
                icon: 'mat_outline:arrow_right',
                hidden: false,
                link: '/pg-link/2',
                module: ['pg-link-2'],
            },
            {
                id: 'PG Link-3',
                title: 'PG Link-3',
                type: 'basic',
                icon: 'mat_outline:arrow_right',
                hidden: false,
                link: '/pg-link/3',
                module: ['pg-link-3'],
            },
          
        ]
    },
    

    // {
    //     id: 'Loan Lead',
    //     title: 'Loan Lead',
    //     type: 'basic',
    //     icon: 'mat_outline:account_balance',
    //     link: '/loan-lead',
    //     module: ['loan-lead'],
    // },
    // {
    //     id: 'Mail',
    //     title: 'Mail',
    //     type: 'basic',
    //     icon: 'mat_outline:mail',
    //     link: '/mail',
    //     module: ['mail'],
    // },

]